config/routes.rb
Rails.application.routes.draw do
  root to: 'registrations#index'

  resources :drugs
  resources :exams
  resources :patients
  resources :prescriptions
  resources :registrations

  post 'login', to: 'registrations#login'
  get 'logout', to: 'registrations#logout'
end

app/models/drug.rb
class Drug < BaseModel
  attribute :id, :integer
  attribute :name, :string

  validates_presence_of :name

  ENDPOINT = '/drug'.freeze

  CUSTOM_ATTRIBUTES = {
    id: 'drugId',
    name: 'drugName'
  }
end

app/controllers/drugs_controller.rb
class DrugsController < ApplicationController
  before_action :set_drug, only: %i[ show edit update destroy ]
  before_action :check_session

  # GET /drugs or /drugs.json
  def index
    @drugs = Drug.all
  end

  # GET /drugs/1 or /drugs/1.json
  def show
  end

  # GET /drugs/new
  def new
    @drug = Drug.new
  end

  # GET /drugs/1/edit
  def edit
  end

  # POST /drugs or /drugs.json
  def create
    @drug = Drug.new(drug_params)

    respond_to do |format|
      if @drug.save
        format.html { redirect_to drugs_url(@drug), notice: "Drug was successfully created." }
        format.json { render :show, status: :created, location: @drug }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /drugs/1 or /drugs/1.json
  def update
    respond_to do |format|
      if @drug.update(drug_params)
        format.html { redirect_to drug_url(@drug), notice: "Drug was successfully updated." }
        format.json { render :show, status: :ok, location: @drug }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @drug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /drugs/1 or /drugs/1.json
  def destroy
    @drug.destroy

    respond_to do |format|
      format.html { redirect_to drugs_url, notice: "Drug was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_drug
    @drug = Drug.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def drug_params
    params.require(:drug).permit(:id, :name)
  end
end

app/helpers/drugs_helper.rb
module DrugsHelper
end

app/views/drugs/_form.html.erb
<%= form_with(model: drug, local: true) do |form| %>
  <% if drug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(drug.errors.count, "error") %> prohibited this drug from being saved:</h2>

      <ul>
        <% drug.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label "Nome do Medicamento" %>
      <%= form.text_field :name, class: "form-control", required: true %>
    </div>

    <br>
    <%= form.hidden_field :patient_id, value: session[:id] %>
    <%= form.submit "Criar", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/drugs/edit.html.erb
<%= link_to "/drugs/#{params[:id]}" do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>
<br>

<h1>Editar Medicamento</h1>

<%= render 'form', drug: @drug %>

app/views/drugs/index.html.erb
<%= link_to "patients/#{session[:id]}" do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>
<br>

<%= link_to new_drug_path do %>
  <i class="material-icons icon-blue">add</i>Adicionar Medicamento
<% end %>
<br>
<br>
<table class="table">
  <thead>
  <tr>
    <th>Nome</th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @drugs.each do |drug| %>
    <tr>
      <td><a href="/drugs/<%= drug.id %>"><%= drug.name %></a></td>
      <td>
        <%= link_to drug, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
          <i class="material-icons icon-blue">delete_forever</i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/drugs/new.html.erb
<h1>Adicionar Medicamento</h1>
<%= link_to drugs_path do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>
<br>

<%= render 'form', drug: @drug %>

app/views/drugs/show.html.erb
<%= link_to "/patients/#{session[:id]}" do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>
<br>

<ul class="list-group">
  <li class="list-group-item active" aria-current="true">Nome do Medicamento
  <li class="list-group-item"><%= @drug.name %></li>
  <li class="list-group-item">Qual a frequência que você toma o medicamento?</li>
  <li class="list-group-item">
    <%= radio_button_tag 'frequency', '3', true %> Uma vez ao dia<br>
    <%= radio_button_tag 'frequency', '3' %> Duas vezes ao dia<br>
    <%= radio_button_tag 'frequency', '3' %> Outra Frequência
  </li>
</ul>

<br>
<%= link_to edit_drug_path(@drug) do %>
  <i class="material-icons icon-blue">edit</i> Editar
<% end %>