config/routes.rb
Rails.application.routes.draw do
  root to: 'registrations#index'

  resources :drugs
  resources :exams
  resources :patients
  resources :prescriptions
  resources :registrations

  post 'login', to: 'registrations#login'
  get 'logout', to: 'registrations#logout'
end

app/models/prescription.rb
class Prescription < BaseModel
  ENDPOINT = '/prescription'.freeze

  attribute :id, :integer
  attribute :description, :string
  attribute :date, :string

  CUSTOM_ATTRIBUTES = {
    id: 'prescriptionId',
    description: 'prescription',
    date: 'prescriptionDate',
    patient: {
      'patient' => {
        id: 'patientId',
        name: 'name',
        email: 'email',
        cpf: 'cpf',
        password: 'password'
      }
    },
    drug: {
      'drug' => {
        id: 'drugId',
        name: 'drugName'
      }
    }
  }

  attr_accessor :patient, :drug

  def full_date
    Date.parse(date).strftime('%d/%m/%Y')
  end

  def date_for_select
    return unless date
    Date.parse(date).strftime('%Y-%m-%d')
  end

  def attr_to_request(data)
    data['prescriptionTime'] = Date.today.strftime("%Y-%m-%dT00:00:00.257Z")

    data
  end
end

app/controllers/prescriptions_controller.rb
class PrescriptionsController < ApplicationController
  before_action :set_prescription, only: %i[ show edit update destroy ]

  # GET /prescriptions or /prescriptions.json
  def index
    @prescriptions = Prescription.all
  end

  # GET /prescriptions/1 or /prescriptions/1.json
  def show
  end

  # GET /prescriptions/new
  def new
    @prescription = Prescription.new
    @drugs = ['Selecione', nil] #Drug.all.map { |drug| [drug.name, drug.id] }
  end

  # GET /prescriptions/1/edit
  def edit
  end

  # POST /prescriptions or /prescriptions.json
  def create
    @prescription = Prescription.new(prescription_params)
    @prescription.patient = Patient.new(prescription_params[:patient])
    @prescription.drug = Drug.new(prescription_params[:drug])

    respond_to do |format|
      if @prescription.save
        format.html { redirect_to prescription_url(@prescription), notice: "Prescription was successfully created." }
        format.json { render :show, status: :created, location: @prescription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prescriptions/1 or /prescriptions/1.json
  def update
    respond_to do |format|
      if @prescription.update(prescription_params)
        format.html { redirect_to prescription_url(@prescription), notice: "Prescription was successfully updated." }
        format.json { render :show, status: :ok, location: @prescription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prescription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prescriptions/1 or /prescriptions/1.json
  def destroy
    @prescription.destroy

    respond_to do |format|
      format.html { redirect_to prescriptions_url, notice: "Prescription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_prescription
    @prescription = Prescription.find(params[:id])
  end

  def prescription_params
    params.require(:prescription).permit(
      [
        :id,
        :description,
        {
          patient: [
            :id,
          ]
        },
        {
          drug: [
            :id,
          ]
        }
      ]
    )
  end
end

app/helpers/prescriptions_helper.rb
module PrescriptionsHelper
end

app/views/prescriptions/_form.html.erb
<%= form_with(model: prescription, local: true) do |form| %>
  <% if prescription.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(prescription.errors.count, "error") %> prohibited this prescription from being saved:</h2>

      <ul>
        <% prescription.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label :description %>
      <%= form.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.fields_for :patient do |p| %>
        <%= prescription.patient.id %>
        <div class="mb-3">
          <%= form.label :patient %>
          <%= p.text_field :id %>
        </div>
      <% end %>
      <% if false %>
        <%= form.fields_for :drug do |p| %>
          <div class="form-group">
            <%= form.label :id %>
            <%= p.select :id, options_for_select(@drugs, nil), { include_blank: 'Selecione' }, { class: "form-select" } %>
          </div>
        <% end %>
      <% end %>
      <%= form.submit %>
    </div>
<% end %>

app/views/prescriptions/edit.html.erb
<h1>Editing Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Show', @prescription %> |
<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Prescriptions</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @prescriptions.each do |prescription| %>
      <tr>
        <td><%= link_to 'Show', prescription %></td>
        <td><%= link_to 'Edit', edit_prescription_path(prescription) %></td>
        <td><%= link_to 'Destroy', prescription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Prescription', new_prescription_path %>

app/views/prescriptions/new.html.erb
<h1>New Prescription</h1>

<%= render 'form', prescription: @prescription %>

<%= link_to 'Back', prescriptions_path %>

app/views/prescriptions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_prescription_path(@prescription) %> |
<%= link_to 'Back', prescriptions_path %>