config/routes.rb
Rails.application.routes.draw do
  root to: 'registrations#index'

  resources :drugs
  resources :exams
  resources :patients
  resources :prescriptions
  resources :registrations

  post 'login', to: 'registrations#login'
  get 'logout', to: 'registrations#logout'
end

app/models/patient.rb
class Patient < BaseModel
  attribute :id, :integer
  attribute :name, :string
  attribute :email, :string
  attribute :cpf, :string
  attribute :password, :string

  ENDPOINT = '/userdetails'.freeze

  CUSTOM_ATTRIBUTES = {
    id: 'userId',
    name: 'name',
    email: 'email',
    cpf: 'cpf',
    password: 'password'
  }
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        session[:id] = @patient.id
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to patient_url(@patient), notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy

    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_patient
    @patient = Patient.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def patient_params
    params.require(:patient).permit(:id, :name, :email, :cpf, :password)
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-group">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :email %>
      <%= form.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= form.label :cpf %>
      <%= form.text_field :cpf, class: "form-control" %>
    </div>

    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pacientes</h1>

<table class="table">
  <thead>
  <tr>
    <th>ID</th>
    <th>Nome</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @patients.each do |patient| %>
    <tr>
      <td><%= patient.id %></td>
      <td><%= patient.name %></td>
      <td><%= link_to 'Show', patient %></td>
      <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
      <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<div style="text-align: center;">
  <i class="material-icons icon-gray large">person</i><br>
  <%= @patient.name %>
</div>

<table class="table">
  <thead>
  <tbody>
  <tr>
    <td>
      <%= link_to drugs_path do %>
        <i class="material-icons icon-blue">assignment_turned_in</i>Controle de Medicamentos
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to exams_path do %>
        <i class="material-icons icon-blue">content_paste</i>Registro de Exames
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to '#' do %>
        <i class="material-icons icon-blue">chat</i>Fale Conosco
      <% end %>
    </td>
  </tr>
  <tr>
    <td>
      <%= link_to '#' do %>
        <i class="material-icons icon-blue">person_add</i>Alteração de Dados
      <% end %>
    </td>
  </tr>
  </tbody>
</table>

<div style="text-align: center;"><%= link_to 'SAIR', registrations_path, class: 'btn btn-primary' %></div>