config/routes.rb
Rails.application.routes.draw do
  root to: 'registrations#index'

  resources :drugs
  resources :exams
  resources :patients
  resources :prescriptions
  resources :registrations

  post 'login', to: 'registrations#login'
  get 'logout', to: 'registrations#logout'
end

app/models/exam.rb
class Exam < BaseModel
  attribute :id, :integer
  attribute :result, :string
  attribute :date, :string

  validates_presence_of :result, :date

  ENDPOINT = '/examentry'.freeze

  CUSTOM_ATTRIBUTES = {
    id: 'examEntryId',
    result: 'examResult',
    date: 'examDateTime',
    patient: {
      'patient' => {
        id: 'patientId',
        name: 'name',
        email: 'email',
        cpf: 'cpf',
        password: 'password'
      }
    },
    exam_type: {
      'examType' => {
        id: 'examTypeId',
        name: 'examName'
      }
    }
  }

  attr_accessor :patient, :exam_type

  def full_date
    Date.parse(date).strftime('%d/%m/%Y')
  end

  def date_for_select
    return Date.today.strftime('%Y-%m-%d') unless date

    Date.parse(date).strftime('%Y-%m-%d')
  end

  def attr_to_request(data)
    data['examDateTime'] = Date.parse(date)
                               .strftime("%Y-%m-%dT00:00:00.257Z")

    data
  end
end

app/models/exam_type.rb
class ExamType < BaseModel
  attribute :id, :integer
  attribute :name, :string

  ENDPOINT = '/examtype'.freeze
  CUSTOM_ATTRIBUTES = {
    id: 'examTypeId',
    name: 'examName'
  }

  def self.all
    response = RequestService::get(ENDPOINT)
    return [] unless response

    response["content"].map do |resource|
      attr = {
        id: resource['examTypeId'],
        name: resource['examName']
      }

      ExamType.new(attr)
    end
  end
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  before_action :set_exam, only: %i[ show edit update destroy ]
  before_action :check_session

  # GET /exams or /exams.json
  def index
    @exams = Exam.all
    @exams.map(&:attributes)
  end

  # GET /exams/1 or /exams/1.json
  def show
    @exam = Exam.find(params[:id])
  end

  # GET /exams/new
  def new
    @exam = Exam.new
    @patient = Patient.new
    @patients = Patient.all.map { |p| ["ID: #{p.id} - #{p.name}", p.id] }
    @exam_types = ExamType.all.map { |p| ["ID: #{p.id} - #{p.name}", p.id] }
  end

  # GET /exams/1/edit
  def edit
    @exam = Exam.find(params[:id])
    @patients = Patient.all.map { |p| ["ID: #{p.id} - #{p.name}", p.id] }
    @exam_types = ExamType.all.map { |p| ["ID: #{p.id} - #{p.name}", p.id] }
  end

  # POST /exams or /exams.json
  def create
    @exam = Exam.new(exam_params)
    @exam.patient = Patient.new(exam_params[:patient])
    @exam.exam_type = ExamType.new(exam_params[:exam_type])

    respond_to do |format|
      if @exam.save
        format.html { redirect_to exam_url(@exam), notice: "Exam was successfully created." }
        format.json { render :show, status: :created, location: @exam }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exams/1 or /exams/1.json
  def update
    respond_to do |format|
      if @exam.update(exam_params)
        format.html { redirect_to exam_url(@exam), notice: "Exam was successfully updated." }
        format.json { render :show, status: :ok, location: @exam }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @exam.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exams/1 or /exams/1.json
  def destroy
    @exam.destroy

    respond_to do |format|
      format.html { redirect_to exams_url, notice: "Exam was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_exam
    @exam = Exam.find(params[:id])
  end

  def exam_params
    params.require(:exam).permit(
      [
        :id,
        :result,
        :date,
        {
          patient: [
            :id,
            :name,
            :email,
            :cpf
          ]
        },
        {
          exam_type: [
            :id,
            :name
          ]
        }
      ]
    )
  end
end

app/helpers/exams_helper.rb
module ExamsHelper
end

app/views/exams/_form.html.erb
<%= form_with(model: exam, local: true) do |form| %>
  <% if exam.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(exam.errors.count, "error") %> prohibited this exam from being saved:</h2>

      <ul>
        <% exam.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    Resultado
    <div class="mb-3">
      <%= form.text_field :result, class: "form-control percent", placeholder: "10%", required: true %>
    </div>

    Data do Exame
    <div class="mb-3">
      <%= form.text_field :date, value: exam.date_for_select, class: "form-control", type: :date %>
    </div>

    <%= form.fields_for :patient do |p| %>
      <div class="mb-3">
        <%= p.hidden_field :id, value: session[:id] %>
      </div>
    <% end %>

    <%= form.fields_for :exam_type do |p| %>
      <div class="form-group">
        Tipo do Exame
        <%= p.select :id, options_for_select(@exam_types), { required: true }, { class: "form-select" } %>
      </div>
    <% end %>

    <% if (false) %>
      <%= form.fields_for :patient do |c| %>
        <div class="form-group">
          <%= form.label :name %>
          <%= c.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :email %>
          <%= c.text_field :email, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :cpf %>
          <%= c.text_field :cpf, class: "form-control" %>
        </div>
      <% end %>

      <%= form.fields_for :exam_type do |c| %>
        <div class="form-group">
          <%= form.label :id %>
          <%= c.text_field :id, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= form.label :name %>
          <%= c.text_field :name, class: "form-control" %>
        </div>
      <% end %>
    <% end %>
    <br>
    <%= form.submit 'Salvar', class: "btn btn-primary" %>
  </div>
<% end %>

app/views/exams/edit.html.erb
<h1>Editing Exam</h1>

<%= render 'form', exam: @exam %>

<%= link_to 'Show', @exam %> |
<%= link_to 'Back', exams_path %>

app/views/exams/index.html.erb
<%= link_to "patients/#{session[:id]}" do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>
<br>

<%= link_to new_exam_path do %>
  <i class="material-icons icon-blue">add</i>Adicionar Exame
<% end %>

<table class="table">
  <thead>
  <tr>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @exams.each do |exam| %>
    <tr>
      <td><%= link_to "Exame - #{exam.full_date}", exam %></td>
      <td>
        <%= link_to exam, method: :delete, data: { confirm: 'Você tem certeza?' } do %>
          <i class="material-icons icon-blue">delete_forever</i>
        <% end %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/exams/new.html.erb
<%= link_to "/exams" do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>

<h1>Novo Exame</h1>

<%= render 'form', exam: @exam %>

<script>
    $('.percent').mask('##00%', {reverse: true});
</script>

app/views/exams/show.html.erb
<%= link_to "/exams" do %>
  <i class="material-icons icon-blue">arrow_back</i>
<% end %>
<br>
<br>

<ul class="list-group">
  <li class="list-group-item active" aria-current="true">Exame Nº <%= @exam.id %></li>
  <li class="list-group-item">Resultado: <%= @exam.result %></li>
  <li class="list-group-item">Data: <%= @exam.full_date %></li>
  <li class="list-group-item">Exame: <%= @exam.exam_type.id %> | <%= @exam.exam_type.name %></li>
</ul>
<br>
<ul class="list-group">
  <li class="list-group-item active" aria-current="true">ID: <%= @exam.patient.id %>
    Paciente: <%= @exam.patient.name %></li>
  <li class="list-group-item">Email: <%= @exam.patient.email %></li>
  <li class="list-group-item">CPF: <%= @exam.patient.cpf %></li>
</ul>